#pragma once

#define SETTING_x_DEBUG_VERSION false


#define SETTING_x_FRAMES_PER_SECOND 2


#define SETTING_x_NUMBER_OF_IMAGES_DEFAULT 2
#define SETTING_x_NUMBER_OF_IMAGES_MIN 2
#define SETTING_x_NUMBER_OF_IMAGES_MAX 100

#define SETTING_x_NUMBER_OF_ELLIPSES_DEFAULT 100
#define SETTING_x_NUMBER_OF_ELLIPSES_MIN 1
#define SETTING_x_NUMBER_OF_ELLIPSES_MAX 100000

#define SETTING_x_ELLIPSE_SIZE_AT_CREATION_DEFAULT 100
#define SETTING_x_ELLIPSE_SIZE_AT_CREATION_MIN 1
#define SETTING_x_ELLIPSE_SIZE_AT_CREATION_MAX 1000

#define SETTING_x_ELLIPSE_MUTATION_CHANCE_DEFAULT 40
#define SETTING_x_ELLIPSE_MUTATION_CHANCE_MIN 1
#define SETTING_x_ELLIPSE_MUTATION_CHANCE_MAX 100000

#define SETTING_x_ELLIPSE_SHAPE_MUTATION_RANGE_DEFAULT 10
#define SETTING_x_ELLIPSE_SHAPE_MUTATION_RANGE_MIN 1
#define SETTING_x_ELLIPSE_SHAPE_MUTATION_RANGE_MAX 1000

#define SETTING_x_ELLIPSE_COLOR_MUTATION_RANGE_DEFAULT 30
#define SETTING_x_ELLIPSE_COLOR_MUTATION_RANGE_MIN 1
#define SETTING_x_ELLIPSE_COLOR_MUTATION_RANGE_MAX 255

#define SETTING_x_BOUNDING_BOX_MARGIN_DEFAULT 20
#define SETTING_x_BOUNDING_BOX_MARGIN_MIN 0
#define SETTING_x_BOUNDING_BOX_MARGIN_MAX 100

#define SETTING_x_COMPARISON_PRECISION_DEFAULT 2
#define SETTING_x_COMPARISON_PRECISION_MIN 1
#define SETTING_x_COMPARISON_PRECISION_MAX 100


#define SETTING_x_MARGIN_TOP 20
#define SETTING_x_MARGIN_LEFT 15
#define SETTING_x_FIELD_HEIGHT 22
#define SETTING_x_FIELD_WIDTH 100
#define SETTING_x_FIELDS_GAP 25
#define SETTING_x_TEXT_AND_FIELD_HORIZONTAL_GAP 20
#define SETTING_x_FONT_SIZE 18
#define SETTING_x_TEXT_WIDTH 500

#define SETTING_x_FILEPATH_FIELD_WIDTH 500
#define SETTING_x_BROWSE_BUTTON_LENGTH 100
#define SETTING_x_TEXT_AND_FIELD_VERTICAL_OFFSET 20
#define SETTING_x_EVOLVE_BUTTON_GAP 10
#define SETTING_x_EVOLVE_BUTTON_HEIGHT 35

#define SETTING_x_WORK_WINDOW_BUTTONS_HEIGHT 22

#define SETTING_x_STARTUP_WINDOW_BACKGROUND_COLOR RGB(220, 220, 220)
#define SETTING_x_EVOLUTION_WINDOW_BACKGROUND_COLOR RGB(220, 220, 220)
#define SETTING_x_IMAGE_EVOLUTION_BACKGROUND_COLOR RGB(0, 0, 0)


#define SETTING_x_MINIMUM_SENSIBLE_WORKING_SET_SIZE_x_PIXELS 300
#define SETTING_x_MINIMUM_SENSIBLE_WORKING_SET_SIZE_x_ELLIPSES 3


#define SETTING_x_KEEP_ONE_CORE_RESERVED_FOR_MAIN_WINDOW true
#define SETTING_x_CREATE_WORK_THREADS_FOR_PHYSICAL_PROCESSORS_ONLY true



#define CONSTANT_x_BYTES_PER_PIXEL 4
#define CONSTANT_x_APLHA_CHANNEL_OFFSET 3